"""Attendance status and method lookup values."""

ATTENDANCE_STATUS_PRESENT = "PRESENT"
ATTENDANCE_STATUS_LATE = "LATE"
ATTENDANCE_STATUS_HALF_DAY = "HALF_DAY"
ATTENDANCE_STATUS_ABSENT = "ABSENT"
ATTENDANCE_STATUS_LEAVE = "LEAVE"
ATTENDANCE_STATUS_WEEK_OFF = "WEEK_OFF"

ATTENDANCE_STATUSES = [
    ATTENDANCE_STATUS_PRESENT,
    ATTENDANCE_STATUS_LATE,
    ATTENDANCE_STATUS_HALF_DAY,
    ATTENDANCE_STATUS_ABSENT,
    ATTENDANCE_STATUS_LEAVE,
    ATTENDANCE_STATUS_WEEK_OFF,
]

ATTENDANCE_SOURCE_AUTO_ABSENT = "AUTO_ABSENT"
ATTENDANCE_SOURCE_LEAVE = "LEAVE"
ATTENDANCE_SOURCE_SYSTEM = "SYSTEM"

SYSTEM_ACTOR_ID = "SYSTEM"

ATTENDANCE_METHOD_LOCATION = "LOCATION"
ATTENDANCE_METHOD_MANUAL = "MANUAL"

ATTENDANCE_METHODS = [
    ATTENDANCE_METHOD_LOCATION,
    ATTENDANCE_METHOD_MANUAL,
]

DEFAULT_ATTENDANCE_RADIUS_METERS = 100
DEFAULT_SHIFT_START = "09:00"
LATE_GRACE_MINUTES = 5
HALF_DAY_THRESHOLD_MINUTES = 240  # 4 hours

ATTENDANCE_LOG_CHECK_IN = "CHECK_IN"
ATTENDANCE_LOG_CHECK_OUT = "CHECK_OUT"
ATTENDANCE_LOG_MANUAL_UPDATE = "MANUAL_UPDATE"
ATTENDANCE_LOG_STATUS_CHANGE = "STATUS_CHANGE"
ATTENDANCE_LOG_AUTO_ABSENT = "AUTO_ABSENT"
