"""Leave request status and audit action lookup values."""

LEAVE_STATUS_PENDING = "PENDING"
LEAVE_STATUS_APPROVED = "APPROVED"
LEAVE_STATUS_REJECTED = "REJECTED"

LEAVE_STATUSES = [
    LEAVE_STATUS_PENDING,
    LEAVE_STATUS_APPROVED,
    LEAVE_STATUS_REJECTED,
]

LEAVE_LOG_CREATED = "LEAVE_CREATED"
LEAVE_LOG_APPROVED = "LEAVE_APPROVED"
LEAVE_LOG_REJECTED = "LEAVE_REJECTED"
