MASTER_PRODUCT_NAMES = [
    "Shampoo",
    "Conditioner",
    "Hair Mask",
    "Hair Serum",
    "Hair Oil",
    "Hair Spa Cream",
    "Hair Color",
    "Hair Bleach",
    "Keratin Treatment Kit",
    "Smoothening Cream",
    "Rebonding Cream",
    "Hair Wax",
    "Hair Gel",
    "Hair Spray",
    "Dry Shampoo",
    "Facial Kit",
    "Face Wash",
    "Scrub",
    "Toner",
    "Moisturizer",
    "Face Serum",
    "Face Pack",
    "Bleach Cream",
    "De-Tan Pack",
    "Sunscreen",
    "Foundation",
    "Compact Powder",
    "Concealer",
    "Primer",
    "Lipstick",
    "Eyeliner",
    "Kajal",
    "Mascara",
    "Makeup Remover",
    "Massage Oil",
    "Body Lotion",
    "Spa Cream",
    "Essential Oil",
    "Nail Paint",
    "Gel Polish",
    "Nail Extension Kit",
    "Rica Wax",
    "Chocolate Wax",
    "Aloe Vera Wax",
    "Beard Oil",
    "Beard Wax",
    "Shaving Cream",
    "After Shave Lotion",
    "L'Oréal Shampoo",
    "Matrix Shampoo",
    "Wella Shampoo",
    "Schwarzkopf Shampoo",
    "Mamaearth Shampoo",
    "Tresemmé Shampoo",
    "Dove Shampoo",
    "BBlunt Shampoo",
    "Olaplex Shampoo",
    "Hair Dryer",
    "Hair Straightener",
    "Hair Curler",
    "Comb Set",
    "Hair Brush",
    "Makeup Brush Kit",
    "Beauty Blender",
    "Nail Cutter",
    "Face Roller",
    "Foot Scrubber",
    "Spa Candle",
    "Bath Salt",
    "Hand Cream",
    "Foot Cream",
    "Lip Balm",
    "Aloe Vera Gel",
    "Charcoal Mask",
    "Vitamin C Serum",
    "Anti Hair Fall Shampoo",
    "Anti Dandruff Shampoo",
    "Protein Shampoo",
    "Color Protection Shampoo",
]
