MASTER_SERVICE_NAMES = [
    "Hair Cut",
    "Men Hair Cut",
    "Women Hair Cut",
    "Kids Hair Cut",
    "Senior Citizen Hair Cut",
    "Beard Trim",
    "Beard Styling",
    "Clean Shave",
    "Mustache Trim",
    "Hair Wash",
    "Hair Spa",
    "Head Massage",
    "Scalp Treatment",
    "Deep Conditioning",
    "Blow Dry",
    "Hair Styling",
    "Hair Straightening",
    "Hair Smoothening",
    "Hair Rebonding",
    "Keratin Treatment",
    "Botox Hair Treatment",
    "Hair Curling",
    "Hair Ironing",
    "Hair Crimping",
    "Global Hair Color",
    "Root Touch Up",
    "Hair Highlights",
    "Balayage",
    "Ombre Hair Color",
    "Fashion Hair Color",
    "Beard Color",
    "Facial",
    "Gold Facial",
    "Diamond Facial",
    "Fruit Facial",
    "Cleanup",
    "De-Tan",
    "Bleach",
    "Hydra Facial",
    "Acne Facial",
    "Anti-Aging Facial",
    "Skin Polishing",
    "Bridal Makeup",
    "Party Makeup",
    "Engagement Makeup",
    "Reception Makeup",
    "HD Makeup",
    "Airbrush Makeup",
    "Groom Makeup",
    "Saree Draping",
    "Hairstyling for Events",
    "Eyebrow Threading",
    "Upper Lip Threading",
    "Chin Threading",
    "Forehead Threading",
    "Full Face Threading",
    "Full Arms Wax",
    "Half Arms Wax",
    "Full Legs Wax",
    "Half Legs Wax",
    "Underarms Wax",
    "Bikini Wax",
    "Brazilian Wax",
    "Full Body Wax",
    "Rica Wax",
    "Chocolate Wax",
    "Basic Manicure",
    "Spa Manicure",
    "Gel Manicure",
    "Basic Pedicure",
    "Spa Pedicure",
    "Gel Polish",
    "Nail Art",
    "Nail Extension",
    "Acrylic Nails",
    "Nail Refill",
    "Nail Removal",
    "Foot Massage",
    "Body Massage",
    "Aroma Therapy",
    "Relaxation Therapy",
    "Bridal Package",
    "Groom Package",
    "Pre-Bridal Package",
    "Pre-Groom Package",
    "Hair Cut + Beard",
    "Hair Cut + Facial",
    "Facial + Cleanup",
    "Spa Combo",
    "Bridal Combo Package",
]
