export const API_PATHS = {
  EXAMPLE: '/example',
  AUTH: {
    LOGIN: '/auth/login',
    SALON_OWNER_LOGIN: '/auth/salon-owner/login',
    GOOGLE_OAUTH: '/auth/google',
    RESET_PASSWORD: '/auth/reset-password',
    LOGOUT_USER: '/auth/logout',
    RESET_PASSWORD_LINK: '/auth/forgot-password',
  },
  INVITATIONS: {
    CREATE: '/invites',
    LIST: '/invites',
    FORM_OPTIONS: '/invites/form-options',
    VALIDATE: (token: string) => `/invites/${token}`,
    CREATE_PASSWORD: '/invites/create-password',
    ACCEPT: '/invites/accept',
    RESEND: '/invites/resend',
    CANCEL: '/invites/cancel',
  },
  SALON_OWNER: {
    PROFILE: '/salon-owner/profile',
  },
  PROFILE: {
    GET: '/profile',
    UPDATE: '/profile',
    CHANGE_PASSWORD: '/profile/change-password',
    AVATAR_UPLOAD: '/profile/avatar',
    AVATAR_REMOVE: '/profile/avatar/remove',
  },
  EMPLOYEES: {
    LIST: '/employees',
    DETAIL: (id: string) => `/employees/${id}`,
    STATUS: (id: string) => `/employees/${id}/status`,
    RESET_PASSWORD: (id: string) => `/employees/${id}/reset-password`,
  },
  SALON_SERVICES: {
    MASTER_LIST: '/services',
    LIST: '/salon-services',
    DETAIL: (id: string) => `/salon-services/${id}`,
  },
  SALON_PRODUCTS: {
    MASTER_LIST: '/products',
    LIST: '/salon-products',
    DETAIL: (id: string) => `/salon-products/${id}`,
  },
  SALONS: {
    LIST: '/salons/list',
  },
  APPOINTMENTS: {
    TODAY: '/appointments/frontdesk/today',
    CREATE_FRONTDESK: '/appointments/frontdesk',
    LIST: '/appointments/list',
    CLIENTS: '/appointments/clients',
    CLIENT_HISTORY: (id: string) => `/appointments/clients/${id}/history`,
    SERVICES: '/appointments/services',
    SALON_SERVICES: '/appointments/salon-services',
    SALON_PRODUCTS: '/appointments/salon-products',
    STAFF: '/appointments/staff',
  },
  BILLING: {
    BILLS: '/billing/bills',
    BILL_DETAIL: (id: string) => `/billing/bills/${id}`,
  },
  PAYROLL: {
    SALARY_TYPES: '/payroll/salary-types',
    SALARY_STRUCTURE: '/payroll/salary-structure',
    SALARY_STRUCTURE_DETAIL: (id: string) => `/payroll/salary-structure/${id}`,
    GENERATE: '/payroll/generate',
    LIST: '/payroll',
    HISTORY: '/payroll/history',
    HISTORY_BY_EMPLOYEE: (id: string) => `/payroll/history/${id}`,
    PAY: (id: string) => `/payroll/${id}/pay`,
    SLIP: (id: string) => `/payroll/${id}/slip`,
    DETAIL: (id: string) => `/payroll/${id}`,
  },
  MY_EARNINGS: {
    SUMMARY: '/my-earnings/summary',
    DAILY: '/my-earnings/daily',
    WALLET: '/my-earnings/wallet',
    SALARY_HISTORY: '/my-earnings/salary-history',
    SALARY_SLIP: (id: string) => `/my-earnings/salary-history/${id}/slip`,
    BREAKDOWN: '/my-earnings/breakdown',
    ACTIVITY: '/my-earnings/activity',
  },
  CUSTOMER_ANALYTICS: {
    OVERVIEW: '/customer-analytics/overview',
    CUSTOMERS: '/customers',
    CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
    REWARD_SETTINGS: '/reward-settings',
    REWARD_SEGMENTS: '/reward-settings/segments',
    REWARD_SEGMENT_DETAIL: (id: string) => `/reward-settings/segments/${id}`,
  },
};
